name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      otams_changed: ${{ steps.filter.outputs.otams }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            otams:
              - 'OTAMS/**'

  build:
    needs: check-changes
    if: needs.check-changes.outputs.otams_changed == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: OTAMS # Adjust if your project folder is different

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: gradle
          cache-dependency-path: "**/*.gradle*"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create google-services.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "OTAMS/app/google-services.json"
          json: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build --stacktrace

  skip-build:
    needs: check-changes
    if: needs.check-changes.outputs.otams_changed == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip build
        run: echo "No changes in OTAMS folder, skipping build âœ“"
